// Stem configuration and fixed order extracted from app.js

export const stemConfigs = {
  kick: {
    name: 'Kick',
    color: 'red',
    basePrompt: 'deep techno kick drum',
    controls: {
      punch: { type: 'knob', min: 0, max: 100, default: 70, unit: '%', label: 'Punch' },
      attack: { type: 'knob', min: 0, max: 100, default: 60, unit: '%', label: 'Attack' },
      decay: { type: 'knob', min: 0, max: 100, default: 40, unit: '%', label: 'Decay' },
      body: { type: 'knob', min: 0, max: 100, default: 50, unit: '%', label: 'Body' },
      tone: { type: 'knob', min: 0, max: 100, default: 50, unit: '%', label: 'Tone' },
      distortion: { type: 'toggle', default: false, label: 'Distortion' },
      rumble: { type: 'toggle', default: false, label: 'Rumble' },
      volume: { type: 'knob', min: 0, max: 100, default: 80, unit: '%', label: 'Volume' },
    },
  },
  perc: {
    name: 'Snare',
    color: 'cyan',
    basePrompt: 'industrial techno snare',
    controls: {
      intensity: { type: 'knob', min: 0, max: 100, default: 60, unit: '%', label: 'Intensity' },
      variation: { type: 'knob', min: 0, max: 100, default: 40, unit: '%', label: 'Variation' },
      snap: { type: 'knob', min: 0, max: 100, default: 60, unit: '%', label: 'Snap' },
      decay: { type: 'knob', min: 0, max: 100, default: 50, unit: '%', label: 'Decay' },
      tone: { type: 'knob', min: 0, max: 100, default: 50, unit: '%', label: 'Tone' },
      metallic: { type: 'toggle', default: false, label: 'Metallic' },
      reverb: { type: 'toggle', default: false, label: 'Reverb' },
      volume: { type: 'knob', min: 0, max: 100, default: 80, unit: '%', label: 'Volume' },
    },
  },
  bass: {
    name: 'Bass',
    color: 'yellow',
    basePrompt: 'dark techno bassline',
    controls: {
      depth: { type: 'knob', min: 0, max: 100, default: 80, unit: '%', label: 'Depth' },
      movement: { type: 'knob', min: 0, max: 100, default: 30, unit: '%', label: 'Movement' },
      attack: { type: 'knob', min: 0, max: 100, default: 50, unit: '%', label: 'Attack' },
      tone: { type: 'knob', min: 0, max: 100, default: 50, unit: '%', label: 'Tone' },
      sub: { type: 'knob', min: 0, max: 100, default: 60, unit: '%', label: 'Sub' },
      filter: { type: 'toggle', default: true, label: 'Filter Sweep' },
      distortion: { type: 'toggle', default: false, label: 'Distortion' },
      volume: { type: 'knob', min: 0, max: 100, default: 80, unit: '%', label: 'Volume' },
    },
  },
  lead: {
    name: 'Lead',
    color: 'green',
    basePrompt: 'hypnotic techno lead synth',
    controls: {
      brightness: { type: 'knob', min: 0, max: 100, default: 50, unit: '%', label: 'Brightness' },
      complexity: { type: 'knob', min: 0, max: 100, default: 40, unit: '%', label: 'Complexity' },
      motion: { type: 'knob', min: 0, max: 100, default: 50, unit: '%', label: 'Motion' },
      attack: { type: 'knob', min: 0, max: 100, default: 50, unit: '%', label: 'Attack' },
      range: { type: 'knob', min: 0, max: 100, default: 50, unit: '%', label: 'Range' },
      delay: { type: 'toggle', default: false, label: 'Delay' },
      chorus: { type: 'toggle', default: false, label: 'Chorus' },
      volume: { type: 'knob', min: 0, max: 100, default: 80, unit: '%', label: 'Volume' },
    },
  },
  hihat: {
    name: 'Hihat',
    color: 'orange',
    basePrompt: 'crisp techno closed hi-hat',
    controls: {
      brightness: { type: 'knob', min: 0, max: 100, default: 60, unit: '%', label: 'Brightness' },
      pattern: { type: 'knob', min: 0, max: 100, default: 50, unit: '%', label: 'Pattern' },
      decay: { type: 'knob', min: 0, max: 100, default: 40, unit: '%', label: 'Decay' },
      texture: { type: 'knob', min: 0, max: 100, default: 50, unit: '%', label: 'Texture' },
      shuffle: { type: 'knob', min: 0, max: 100, default: 40, unit: '%', label: 'Shuffle' },
      reverb: { type: 'toggle', default: false, label: 'Reverb' },
      chorus: { type: 'toggle', default: false, label: 'Chorus' },
      volume: { type: 'knob', min: 0, max: 100, default: 80, unit: '%', label: 'Volume' },
    },
  },
  pad: {
    name: 'Pad',
    color: 'purple',
    basePrompt: 'ambient techno pad',
    controls: {
      warmth: { type: 'knob', min: 0, max: 100, default: 60, unit: '%', label: 'Warmth' },
      evolution: { type: 'knob', min: 0, max: 100, default: 30, unit: '%', label: 'Evolution' },
      brightness: { type: 'knob', min: 0, max: 100, default: 50, unit: '%', label: 'Brightness' },
      motion: { type: 'knob', min: 0, max: 100, default: 50, unit: '%', label: 'Motion' },
      texture: { type: 'knob', min: 0, max: 100, default: 50, unit: '%', label: 'Texture' },
      chorus: { type: 'toggle', default: true, label: 'Chorus' },
      reverb: { type: 'toggle', default: false, label: 'Reverb' },
      volume: { type: 'knob', min: 0, max: 100, default: 80, unit: '%', label: 'Volume' },
    },
  },
  arp: {
    name: 'Arp',
    color: 'blue',
    basePrompt: 'techno synthesizer arpeggio',
    controls: {
      rate: { type: 'knob', min: 0, max: 100, default: 55, unit: '%', label: 'Rate' },
      complexity: { type: 'knob', min: 0, max: 100, default: 60, unit: '%', label: 'Complexity' },
      range: { type: 'knob', min: 0, max: 100, default: 50, unit: '%', label: 'Range' },
      swing: { type: 'knob', min: 0, max: 100, default: 50, unit: '%', label: 'Swing' },
      tone: { type: 'knob', min: 0, max: 100, default: 50, unit: '%', label: 'Tone' },
      gate: { type: 'toggle', default: false, label: 'Long Gate' },
      delay: { type: 'toggle', default: false, label: 'Delay' },
      volume: { type: 'knob', min: 0, max: 100, default: 80, unit: '%', label: 'Volume' },
    },
  },
  fx: {
    name: 'FX',
    color: 'pink',
    basePrompt: 'techno transition effects and atmos',
    controls: {
      intensity: { type: 'knob', min: 0, max: 100, default: 65, unit: '%', label: 'Intensity' },
      movement: { type: 'knob', min: 0, max: 100, default: 50, unit: '%', label: 'Movement' },
      texture: { type: 'knob', min: 0, max: 100, default: 50, unit: '%', label: 'Texture' },
      sweep: { type: 'knob', min: 0, max: 100, default: 50, unit: '%', label: 'Sweep' },
      filter: { type: 'knob', min: 0, max: 100, default: 50, unit: '%', label: 'Filter' },
      reverb: { type: 'toggle', default: true, label: 'Reverb' },
      delay: { type: 'toggle', default: false, label: 'Delay' },
      volume: { type: 'knob', min: 0, max: 100, default: 80, unit: '%', label: 'Volume' },
    },
  },
  perc2: {
    name: 'Perc',
    color: 'orange',
    basePrompt: 'techno top percussion loop',
    controls: {
      density: { type: 'knob', min: 0, max: 100, default: 60, unit: '%', label: 'Density' },
      groove: { type: 'knob', min: 0, max: 100, default: 50, unit: '%', label: 'Groove' },
      variation: { type: 'knob', min: 0, max: 100, default: 50, unit: '%', label: 'Variation' },
      tone: { type: 'knob', min: 0, max: 100, default: 50, unit: '%', label: 'Tone' },
      syncopation: { type: 'knob', min: 0, max: 100, default: 50, unit: '%', label: 'Syncopation' },
      metallic: { type: 'toggle', default: false, label: 'Metallic' },
      reverb: { type: 'toggle', default: false, label: 'Reverb' },
      volume: { type: 'knob', min: 0, max: 100, default: 80, unit: '%', label: 'Volume' },
    },
  },
}

// Fixed hotkey order (1–9)
export const STEM_ORDER = ['kick','perc','bass','lead','hihat','pad','arp','fx','perc2']


